version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.3
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
  release:
    docker:
      - image: circleci/node:8.3
    steps:
      - checkout
      - run: npm install
      - run: npx semantic-release
workflows:
  version: 2
  test_and_release:
    jobs:
      - build
      - release:
          requires:
            - build